'use client';

import { useCallback, useEffect, useState } from 'react';
import { useLocale, useTranslations } from 'next-intl';
import { apiFetch } from '@/lib/api';
import { tokenStore } from '@/lib/auth';

const LEVELS = ['Beginner', 'Elementary', 'PreIntermediate', 'Intermediate', 'UpperIntermediate', 'Advanced'];
const ASPECTS = ['Grammar', 'Reading', 'Listening', 'Vocabulary', 'Speaking', 'Writing'];

interface Job {
  id: string;
  status: string;
  targetType: string;
  courseId: string | null;
  courseLessonId: string | null;
  error: string | null;
}

// The AI review strip inside the course editor (ФТ-К404/К406). When a generation
// job targets this course it shows the "generated by AI" marker plus Approve
// (course jobs) / Refine; for a draft course it also offers to generate one more
// lesson into it (targetType=LESSON). The эталон never leaves the server — this
// only drives the buttons; all validation/materialisation is server-side.
export function CourseAiPanel({
  courseId,
  courseStatus,
  level,
  onChanged
}: {
  courseId: string;
  courseStatus: string;
  level: string;
  onChanged: () => void;
}) {
  const t = useTranslations('courses');
  const tc = useTranslations('common');
  const locale = useLocale();
  const [job, setJob] = useState<Job | null>(null);
  const [busy, setBusy] = useState(false);
  const [refine, setRefine] = useState('');
  const [genOpen, setGenOpen] = useState(false);
  const [topic, setTopic] = useState('');
  const [genLevel, setGenLevel] = useState(level);
  const [aspects, setAspects] = useState<string[]>(['Grammar']);

  const loadJobs = useCallback(async () => {
    const token = tokenStore.get();
    if (!token) return;
    const jobs = await apiFetch<Job[]>(`/content/generate?courseId=${courseId}`, { token, locale }).catch(() => null);
    setJob(jobs && jobs.length ? jobs[0] : null);
  }, [courseId, locale]);

  useEffect(() => {
    void loadJobs();
  }, [loadJobs]);

  // Poll a running job until it settles, then refresh the tree + the marker.
  const poll = useCallback(
    async (id: string) => {
      const token = tokenStore.get();
      if (!token) return;
      const j = await apiFetch<Job>(`/content/generate/${id}`, { token, locale }).catch(() => null);
      if (!j) return;
      setJob(j);
      if (j.status === 'generating') setTimeout(() => void poll(id), 2000);
      else onChanged();
    },
    [locale, onChanged]
  );

  async function approve() {
    const token = tokenStore.get();
    if (!token || !job) return;
    setBusy(true);
    try {
      await apiFetch(`/content/generate/${job.id}/approve`, { method: 'POST', token, locale });
      await loadJobs();
      onChanged();
    } finally {
      setBusy(false);
    }
  }

  // Refine only the area this job produced: a course job → the whole course, a
  // lesson job → that one lesson (so hand-made lessons are never touched).
  async function doRefine() {
    const token = tokenStore.get();
    if (!token || !job || !refine.trim()) return;
    const scope = job.targetType === 'LESSON' && job.courseLessonId ? `lesson:${job.courseLessonId}` : 'course';
    setBusy(true);
    try {
      const j = await apiFetch<Job>(`/content/generate/${job.id}/revise`, {
        method: 'POST',
        token,
        locale,
        body: { scope, instruction: refine.trim() }
      });
      setRefine('');
      setJob(j);
      setTimeout(() => void poll(j.id), 1500);
    } finally {
      setBusy(false);
    }
  }

  async function genLesson() {
    const token = tokenStore.get();
    if (!token || !topic.trim()) return;
    setBusy(true);
    try {
      const j = await apiFetch<Job>('/content/generate', {
        method: 'POST',
        token,
        locale,
        body: { targetType: 'LESSON', courseId, topic: topic.trim(), level: genLevel, aspects }
      });
      setTopic('');
      setGenOpen(false);
      setJob(j);
      setTimeout(() => void poll(j.id), 1500);
    } finally {
      setBusy(false);
    }
  }

  const generating = job?.status === 'generating';
  const ready = job?.status === 'ready_for_review';
  const toggleAspect = (a: string) =>
    setAspects((p) => (p.includes(a) ? p.filter((x) => x !== a) : [...p, a]));

  // Nothing to show: no AI job on this course and the course is published.
  if (!job && courseStatus !== 'draft') return null;

  return (
    <div className="ai-panel card">
      {job && <span className="ai-badge">{t('aiGenerated')}</span>}
      {generating && <p className="note">{t('aiGenerating')}</p>}
      {ready && (
        <div className="ai-review">
          <p className="note">{t('aiReady')}</p>
          {job?.targetType !== 'LESSON' && (
            <button type="button" disabled={busy} onClick={approve}>{t('aiApprove')}</button>
          )}
          <label>{t('refineInstruction')}<input value={refine} onChange={(e) => setRefine(e.target.value)} /></label>
          <button type="button" className="ghost" disabled={busy || !refine.trim()} onClick={doRefine}>{t('refine')}</button>
        </div>
      )}
      {job?.status === 'approved' && <p className="note">{t('aiApproved')}</p>}
      {job?.status === 'failed' && (
        <p className="error">{t('aiFailed')}{job.error ? `: ${job.error}` : ''}</p>
      )}

      {courseStatus === 'draft' && !generating && (
        <div className="ai-genlesson">
          {genOpen ? (
            <div className="form-grid">
              <label>{t('aiTopic')}<input autoFocus value={topic} onChange={(e) => setTopic(e.target.value)} /></label>
              <label>
                {t('level')}
                <select value={genLevel} onChange={(e) => setGenLevel(e.target.value)}>
                  {LEVELS.map((l) => (
                    <option key={l} value={l}>{l}</option>
                  ))}
                </select>
              </label>
              <div className="field">
                <span>{t('aiAspects')}</span>
                <div className="tabs tabs-inline filter-chips">
                  {ASPECTS.map((a) => (
                    <button key={a} type="button" className={aspects.includes(a) ? 'active' : ''} onClick={() => toggleAspect(a)}>
                      {a}
                    </button>
                  ))}
                </div>
              </div>
              <div className="row-actions">
                <button type="button" disabled={busy || !topic.trim()} onClick={genLesson}>{t('aiGenerate')}</button>
                <button type="button" className="ghost" onClick={() => setGenOpen(false)}>{tc('close')}</button>
              </div>
            </div>
          ) : (
            <button type="button" className="ghost" onClick={() => setGenOpen(true)}>{t('aiGenLesson')}</button>
          )}
        </div>
      )}
    </div>
  );
}
