// Starter word bank: high-frequency English with Russian glosses, grouped by
// CEFR level and theme. Bundled rather than fetched — no network call, no
// licence question and no cost, and it makes the bank useful on day one.
// An admin loads it once; importing is an upsert, so loading it twice is safe
// and never overwrites a translation a tutor has corrected by hand.
export const STARTER_WORD_BANK: { topic: string; words: { word: string; translation: string }[] }[] = [
  {
    topic: "A1 · Everyday",
    words: [
      { word: "hello", translation: "привет" },
      { word: "goodbye", translation: "до свидания" },
      { word: "please", translation: "пожалуйста" },
      { word: "thank you", translation: "спасибо" },
      { word: "yes", translation: "да" },
      { word: "no", translation: "нет" },
      { word: "sorry", translation: "извините" },
      { word: "name", translation: "имя" },
      { word: "friend", translation: "друг" },
      { word: "family", translation: "семья" },
      { word: "mother", translation: "мама" },
      { word: "father", translation: "папа" },
      { word: "sister", translation: "сестра" },
      { word: "brother", translation: "брат" },
      { word: "house", translation: "дом" },
      { word: "room", translation: "комната" },
      { word: "door", translation: "дверь" },
      { word: "window", translation: "окно" },
      { word: "table", translation: "стол" },
      { word: "chair", translation: "стул" },
      { word: "water", translation: "вода" },
      { word: "bread", translation: "хлеб" },
      { word: "milk", translation: "молоко" },
      { word: "apple", translation: "яблоко" },
      { word: "food", translation: "еда" },
      { word: "day", translation: "день" },
      { word: "night", translation: "ночь" },
      { word: "week", translation: "неделя" },
      { word: "month", translation: "месяц" },
      { word: "year", translation: "год" },
      { word: "today", translation: "сегодня" },
      { word: "tomorrow", translation: "завтра" },
      { word: "yesterday", translation: "вчера" },
      { word: "morning", translation: "утро" },
      { word: "evening", translation: "вечер" },
      { word: "city", translation: "город" },
      { word: "street", translation: "улица" },
      { word: "car", translation: "машина" },
      { word: "book", translation: "книга" },
      { word: "school", translation: "школа" },
    ],
  },
  {
    topic: "A2 · Daily life",
    words: [
      { word: "job", translation: "работа" },
      { word: "money", translation: "деньги" },
      { word: "shop", translation: "магазин" },
      { word: "price", translation: "цена" },
      { word: "cheap", translation: "дешёвый" },
      { word: "expensive", translation: "дорогой" },
      { word: "busy", translation: "занятый" },
      { word: "free", translation: "свободный" },
      { word: "early", translation: "рано" },
      { word: "late", translation: "поздно" },
      { word: "often", translation: "часто" },
      { word: "never", translation: "никогда" },
      { word: "always", translation: "всегда" },
      { word: "sometimes", translation: "иногда" },
      { word: "weather", translation: "погода" },
      { word: "rain", translation: "дождь" },
      { word: "snow", translation: "снег" },
      { word: "warm", translation: "тёплый" },
      { word: "cold", translation: "холодный" },
      { word: "travel", translation: "путешествовать" },
      { word: "ticket", translation: "билет" },
      { word: "station", translation: "станция" },
      { word: "airport", translation: "аэропорт" },
      { word: "luggage", translation: "багаж" },
      { word: "holiday", translation: "отпуск" },
      { word: "health", translation: "здоровье" },
      { word: "doctor", translation: "врач" },
      { word: "medicine", translation: "лекарство" },
      { word: "tired", translation: "усталый" },
      { word: "happy", translation: "счастливый" },
      { word: "angry", translation: "сердитый" },
      { word: "afraid", translation: "испуганный" },
      { word: "remember", translation: "помнить" },
      { word: "forget", translation: "забывать" },
      { word: "understand", translation: "понимать" },
      { word: "explain", translation: "объяснять" },
      { word: "choose", translation: "выбирать" },
      { word: "decide", translation: "решать" },
      { word: "agree", translation: "соглашаться" },
      { word: "borrow", translation: "занимать (брать)" },
    ],
  },
  {
    topic: "B1 · Work & study",
    words: [
      { word: "meeting", translation: "встреча" },
      { word: "deadline", translation: "срок сдачи" },
      { word: "schedule", translation: "расписание" },
      { word: "task", translation: "задача" },
      { word: "report", translation: "отчёт" },
      { word: "colleague", translation: "коллега" },
      { word: "manager", translation: "руководитель" },
      { word: "salary", translation: "зарплата" },
      { word: "interview", translation: "собеседование" },
      { word: "experience", translation: "опыт" },
      { word: "skill", translation: "навык" },
      { word: "goal", translation: "цель" },
      { word: "improve", translation: "улучшать" },
      { word: "achieve", translation: "достигать" },
      { word: "succeed", translation: "преуспевать" },
      { word: "fail", translation: "терпеть неудачу" },
      { word: "suggest", translation: "предлагать" },
      { word: "discuss", translation: "обсуждать" },
      { word: "solve", translation: "решать (проблему)" },
      { word: "avoid", translation: "избегать" },
      { word: "require", translation: "требовать" },
      { word: "provide", translation: "предоставлять" },
      { word: "increase", translation: "увеличивать" },
      { word: "reduce", translation: "сокращать" },
      { word: "research", translation: "исследование" },
      { word: "evidence", translation: "доказательство" },
      { word: "opinion", translation: "мнение" },
      { word: "reason", translation: "причина" },
      { word: "result", translation: "результат" },
      { word: "effect", translation: "эффект" },
      { word: "advantage", translation: "преимущество" },
      { word: "disadvantage", translation: "недостаток" },
      { word: "compare", translation: "сравнивать" },
      { word: "describe", translation: "описывать" },
      { word: "mention", translation: "упоминать" },
      { word: "prepare", translation: "готовить(ся)" },
      { word: "attend", translation: "посещать" },
      { word: "apply", translation: "подавать заявку" },
      { word: "responsible", translation: "ответственный" },
      { word: "reliable", translation: "надёжный" },
    ],
  },
  {
    topic: "B2 · Opinions & abstract",
    words: [
      { word: "assume", translation: "предполагать" },
      { word: "consider", translation: "рассматривать" },
      { word: "determine", translation: "определять" },
      { word: "emphasise", translation: "подчёркивать" },
      { word: "indicate", translation: "указывать" },
      { word: "interpret", translation: "истолковывать" },
      { word: "maintain", translation: "утверждать; поддерживать" },
      { word: "obtain", translation: "получать" },
      { word: "occur", translation: "происходить" },
      { word: "perceive", translation: "воспринимать" },
      { word: "pursue", translation: "преследовать (цель)" },
      { word: "reveal", translation: "раскрывать" },
      { word: "significant", translation: "значительный" },
      { word: "substantial", translation: "существенный" },
      { word: "inevitable", translation: "неизбежный" },
      { word: "controversial", translation: "спорный" },
      { word: "reluctant", translation: "неохотный" },
      { word: "thorough", translation: "тщательный" },
      { word: "accurate", translation: "точный" },
      { word: "relevant", translation: "уместный" },
      { word: "sufficient", translation: "достаточный" },
      { word: "crucial", translation: "решающий" },
      { word: "approach", translation: "подход" },
      { word: "attitude", translation: "отношение" },
      { word: "consequence", translation: "последствие" },
      { word: "assumption", translation: "допущение" },
      { word: "estimate", translation: "оценка; оценивать" },
      { word: "tendency", translation: "тенденция" },
      { word: "circumstances", translation: "обстоятельства" },
      { word: "bias", translation: "предвзятость" },
    ],
  },
  {
    topic: "Phrasal verbs",
    words: [
      { word: "give up", translation: "сдаваться; бросать" },
      { word: "look for", translation: "искать" },
      { word: "look after", translation: "заботиться о" },
      { word: "find out", translation: "выяснять" },
      { word: "turn on", translation: "включать" },
      { word: "turn off", translation: "выключать" },
      { word: "put off", translation: "откладывать" },
      { word: "take off", translation: "снимать; взлетать" },
      { word: "get up", translation: "вставать" },
      { word: "come back", translation: "возвращаться" },
      { word: "go on", translation: "продолжать" },
      { word: "carry out", translation: "выполнять" },
      { word: "point out", translation: "указывать на" },
      { word: "set up", translation: "учреждать; настраивать" },
      { word: "deal with", translation: "иметь дело с" },
      { word: "bring up", translation: "воспитывать; поднимать (тему)" },
      { word: "run out of", translation: "заканчиваться (о запасе)" },
      { word: "catch up", translation: "догонять" },
      { word: "work out", translation: "получаться; тренироваться" },
      { word: "figure out", translation: "разобраться" },
    ],
  },
  {
    topic: "Business",
    words: [
      { word: "negotiate", translation: "вести переговоры" },
      { word: "contract", translation: "договор" },
      { word: "invoice", translation: "счёт" },
      { word: "budget", translation: "бюджет" },
      { word: "revenue", translation: "выручка" },
      { word: "profit", translation: "прибыль" },
      { word: "loss", translation: "убыток" },
      { word: "client", translation: "клиент" },
      { word: "supplier", translation: "поставщик" },
      { word: "stakeholder", translation: "заинтересованная сторона" },
      { word: "launch", translation: "запуск; запускать" },
      { word: "deliver", translation: "поставлять; доставлять" },
      { word: "scale", translation: "масштабировать" },
      { word: "forecast", translation: "прогноз" },
      { word: "target", translation: "цель; целевой показатель" },
      { word: "share", translation: "доля; акция" },
      { word: "merger", translation: "слияние" },
      { word: "bankrupt", translation: "банкрот" },
      { word: "competitor", translation: "конкурент" },
      { word: "agenda", translation: "повестка" },
    ],
  },
];
