// Starter word bank: high-frequency English, each entry glossed in every UI
// locale. Bundled rather than fetched — no network call, no licence question
// and no cost — so the bank is useful the moment the platform is installed.
//
// `en` is a short definition rather than a translation: for an English course
// the English column is what the word MEANS, not what it is called. The UI
// shows that definition first and reveals the reader's own language on request.
//
// Loading is idempotent: words already in the bank are skipped, so re-running
// adds nothing and never overwrites a gloss a tutor corrected by hand.
export interface StarterWord {
  word: string;
  /** locale -> gloss; `ru` doubles as the stored default translation. */
  translations: Record<string, string>;
}

export const STARTER_WORD_BANK: { topic: string; words: StarterWord[] }[] = [
  {
    topic: "A1 · Everyday",
    words: [
      { word: "hello", translations: { en: "a greeting", ru: "привет", de: "hallo", fr: "bonjour", nl: "hallo", ar: "مرحبا" } },
      { word: "goodbye", translations: { en: "said when leaving", ru: "до свидания", de: "tschüss", fr: "au revoir", nl: "tot ziens", ar: "وداعا" } },
      { word: "please", translations: { en: "polite request word", ru: "пожалуйста", de: "bitte", fr: "s'il vous plaît", nl: "alsjeblieft", ar: "من فضلك" } },
      { word: "thank you", translations: { en: "expression of thanks", ru: "спасибо", de: "danke", fr: "merci", nl: "dank je", ar: "شكرا" } },
      { word: "sorry", translations: { en: "apology", ru: "извините", de: "entschuldigung", fr: "pardon", nl: "sorry", ar: "آسف" } },
      { word: "name", translations: { en: "what someone is called", ru: "имя", de: "Name", fr: "nom", nl: "naam", ar: "اسم" } },
      { word: "friend", translations: { en: "a person you like", ru: "друг", de: "Freund", fr: "ami", nl: "vriend", ar: "صديق" } },
      { word: "family", translations: { en: "parents and children", ru: "семья", de: "Familie", fr: "famille", nl: "familie", ar: "عائلة" } },
      { word: "mother", translations: { en: "female parent", ru: "мама", de: "Mutter", fr: "mère", nl: "moeder", ar: "أم" } },
      { word: "father", translations: { en: "male parent", ru: "папа", de: "Vater", fr: "père", nl: "vader", ar: "أب" } },
      { word: "sister", translations: { en: "female sibling", ru: "сестра", de: "Schwester", fr: "sœur", nl: "zus", ar: "أخت" } },
      { word: "brother", translations: { en: "male sibling", ru: "брат", de: "Bruder", fr: "frère", nl: "broer", ar: "أخ" } },
      { word: "child", translations: { en: "a young person", ru: "ребёнок", de: "Kind", fr: "enfant", nl: "kind", ar: "طفل" } },
      { word: "house", translations: { en: "a building to live in", ru: "дом", de: "Haus", fr: "maison", nl: "huis", ar: "منزل" } },
      { word: "room", translations: { en: "a space in a building", ru: "комната", de: "Zimmer", fr: "pièce", nl: "kamer", ar: "غرفة" } },
      { word: "door", translations: { en: "you open it to enter", ru: "дверь", de: "Tür", fr: "porte", nl: "deur", ar: "باب" } },
      { word: "window", translations: { en: "glass opening in a wall", ru: "окно", de: "Fenster", fr: "fenêtre", nl: "raam", ar: "نافذة" } },
      { word: "table", translations: { en: "furniture with a flat top", ru: "стол", de: "Tisch", fr: "table", nl: "tafel", ar: "طاولة" } },
      { word: "chair", translations: { en: "a seat", ru: "стул", de: "Stuhl", fr: "chaise", nl: "stoel", ar: "كرسي" } },
      { word: "water", translations: { en: "what you drink", ru: "вода", de: "Wasser", fr: "eau", nl: "water", ar: "ماء" } },
      { word: "bread", translations: { en: "baked food", ru: "хлеб", de: "Brot", fr: "pain", nl: "brood", ar: "خبز" } },
      { word: "milk", translations: { en: "white drink", ru: "молоко", de: "Milch", fr: "lait", nl: "melk", ar: "حليب" } },
      { word: "apple", translations: { en: "a round fruit", ru: "яблоко", de: "Apfel", fr: "pomme", nl: "appel", ar: "تفاحة" } },
      { word: "food", translations: { en: "what you eat", ru: "еда", de: "Essen", fr: "nourriture", nl: "eten", ar: "طعام" } },
      { word: "day", translations: { en: "24 hours", ru: "день", de: "Tag", fr: "jour", nl: "dag", ar: "يوم" } },
      { word: "night", translations: { en: "dark hours", ru: "ночь", de: "Nacht", fr: "nuit", nl: "nacht", ar: "ليل" } },
      { word: "week", translations: { en: "seven days", ru: "неделя", de: "Woche", fr: "semaine", nl: "week", ar: "أسبوع" } },
      { word: "month", translations: { en: "about 30 days", ru: "месяц", de: "Monat", fr: "mois", nl: "maand", ar: "شهر" } },
      { word: "year", translations: { en: "twelve months", ru: "год", de: "Jahr", fr: "année", nl: "jaar", ar: "سنة" } },
      { word: "today", translations: { en: "this day", ru: "сегодня", de: "heute", fr: "aujourd'hui", nl: "vandaag", ar: "اليوم" } },
      { word: "tomorrow", translations: { en: "the next day", ru: "завтра", de: "morgen", fr: "demain", nl: "morgen", ar: "غدا" } },
      { word: "yesterday", translations: { en: "the day before", ru: "вчера", de: "gestern", fr: "hier", nl: "gisteren", ar: "أمس" } },
      { word: "morning", translations: { en: "early part of the day", ru: "утро", de: "Morgen", fr: "matin", nl: "ochtend", ar: "صباح" } },
      { word: "evening", translations: { en: "end of the day", ru: "вечер", de: "Abend", fr: "soir", nl: "avond", ar: "مساء" } },
      { word: "city", translations: { en: "a large town", ru: "город", de: "Stadt", fr: "ville", nl: "stad", ar: "مدينة" } },
      { word: "street", translations: { en: "a road in a town", ru: "улица", de: "Straße", fr: "rue", nl: "straat", ar: "شارع" } },
      { word: "car", translations: { en: "a vehicle", ru: "машина", de: "Auto", fr: "voiture", nl: "auto", ar: "سيارة" } },
      { word: "book", translations: { en: "printed pages", ru: "книга", de: "Buch", fr: "livre", nl: "boek", ar: "كتاب" } },
      { word: "school", translations: { en: "where children learn", ru: "школа", de: "Schule", fr: "école", nl: "school", ar: "مدرسة" } },
      { word: "teacher", translations: { en: "a person who teaches", ru: "учитель", de: "Lehrer", fr: "professeur", nl: "docent", ar: "معلم" } },
    ],
  },
  {
    topic: "A2 · Daily life",
    words: [
      { word: "job", translations: { en: "paid work", ru: "работа", de: "Arbeit", fr: "emploi", nl: "baan", ar: "وظيفة" } },
      { word: "money", translations: { en: "what you pay with", ru: "деньги", de: "Geld", fr: "argent", nl: "geld", ar: "مال" } },
      { word: "shop", translations: { en: "where you buy things", ru: "магазин", de: "Geschäft", fr: "magasin", nl: "winkel", ar: "متجر" } },
      { word: "price", translations: { en: "how much it costs", ru: "цена", de: "Preis", fr: "prix", nl: "prijs", ar: "سعر" } },
      { word: "cheap", translations: { en: "low in price", ru: "дешёвый", de: "billig", fr: "bon marché", nl: "goedkoop", ar: "رخيص" } },
      { word: "expensive", translations: { en: "high in price", ru: "дорогой", de: "teuer", fr: "cher", nl: "duur", ar: "غالي" } },
      { word: "busy", translations: { en: "having a lot to do", ru: "занятый", de: "beschäftigt", fr: "occupé", nl: "druk", ar: "مشغول" } },
      { word: "early", translations: { en: "before the usual time", ru: "рано", de: "früh", fr: "tôt", nl: "vroeg", ar: "مبكرا" } },
      { word: "late", translations: { en: "after the usual time", ru: "поздно", de: "spät", fr: "tard", nl: "laat", ar: "متأخرا" } },
      { word: "often", translations: { en: "many times", ru: "часто", de: "oft", fr: "souvent", nl: "vaak", ar: "غالبا" } },
      { word: "never", translations: { en: "at no time", ru: "никогда", de: "nie", fr: "jamais", nl: "nooit", ar: "أبدا" } },
      { word: "always", translations: { en: "every time", ru: "всегда", de: "immer", fr: "toujours", nl: "altijd", ar: "دائما" } },
      { word: "sometimes", translations: { en: "now and then", ru: "иногда", de: "manchmal", fr: "parfois", nl: "soms", ar: "أحيانا" } },
      { word: "weather", translations: { en: "rain, sun, wind", ru: "погода", de: "Wetter", fr: "temps", nl: "weer", ar: "طقس" } },
      { word: "rain", translations: { en: "water falling from clouds", ru: "дождь", de: "Regen", fr: "pluie", nl: "regen", ar: "مطر" } },
      { word: "snow", translations: { en: "frozen white flakes", ru: "снег", de: "Schnee", fr: "neige", nl: "sneeuw", ar: "ثلج" } },
      { word: "warm", translations: { en: "pleasantly hot", ru: "тёплый", de: "warm", fr: "chaud", nl: "warm", ar: "دافئ" } },
      { word: "cold", translations: { en: "low temperature", ru: "холодный", de: "kalt", fr: "froid", nl: "koud", ar: "بارد" } },
      { word: "travel", translations: { en: "go from place to place", ru: "путешествовать", de: "reisen", fr: "voyager", nl: "reizen", ar: "يسافر" } },
      { word: "ticket", translations: { en: "proof you paid to travel", ru: "билет", de: "Fahrkarte", fr: "billet", nl: "kaartje", ar: "تذكرة" } },
      { word: "station", translations: { en: "where trains stop", ru: "станция", de: "Bahnhof", fr: "gare", nl: "station", ar: "محطة" } },
      { word: "airport", translations: { en: "where planes land", ru: "аэропорт", de: "Flughafen", fr: "aéroport", nl: "luchthaven", ar: "مطار" } },
      { word: "luggage", translations: { en: "bags you travel with", ru: "багаж", de: "Gepäck", fr: "bagages", nl: "bagage", ar: "أمتعة" } },
      { word: "holiday", translations: { en: "time off work", ru: "отпуск", de: "Urlaub", fr: "vacances", nl: "vakantie", ar: "عطلة" } },
      { word: "health", translations: { en: "how well your body is", ru: "здоровье", de: "Gesundheit", fr: "santé", nl: "gezondheid", ar: "صحة" } },
      { word: "doctor", translations: { en: "treats sick people", ru: "врач", de: "Arzt", fr: "médecin", nl: "dokter", ar: "طبيب" } },
      { word: "medicine", translations: { en: "what you take when ill", ru: "лекарство", de: "Medikament", fr: "médicament", nl: "medicijn", ar: "دواء" } },
      { word: "tired", translations: { en: "needing rest", ru: "усталый", de: "müde", fr: "fatigué", nl: "moe", ar: "متعب" } },
      { word: "happy", translations: { en: "feeling good", ru: "счастливый", de: "glücklich", fr: "heureux", nl: "blij", ar: "سعيد" } },
      { word: "angry", translations: { en: "feeling strong annoyance", ru: "сердитый", de: "wütend", fr: "en colère", nl: "boos", ar: "غاضب" } },
      { word: "afraid", translations: { en: "feeling fear", ru: "испуганный", de: "ängstlich", fr: "effrayé", nl: "bang", ar: "خائف" } },
      { word: "remember", translations: { en: "keep in your mind", ru: "помнить", de: "erinnern", fr: "se souvenir", nl: "onthouden", ar: "يتذكر" } },
      { word: "forget", translations: { en: "fail to remember", ru: "забывать", de: "vergessen", fr: "oublier", nl: "vergeten", ar: "ينسى" } },
      { word: "understand", translations: { en: "know the meaning", ru: "понимать", de: "verstehen", fr: "comprendre", nl: "begrijpen", ar: "يفهم" } },
      { word: "explain", translations: { en: "make something clear", ru: "объяснять", de: "erklären", fr: "expliquer", nl: "uitleggen", ar: "يشرح" } },
      { word: "choose", translations: { en: "pick one", ru: "выбирать", de: "wählen", fr: "choisir", nl: "kiezen", ar: "يختار" } },
      { word: "decide", translations: { en: "make up your mind", ru: "решать", de: "entscheiden", fr: "décider", nl: "beslissen", ar: "يقرر" } },
      { word: "agree", translations: { en: "have the same opinion", ru: "соглашаться", de: "zustimmen", fr: "être d'accord", nl: "het eens zijn", ar: "يوافق" } },
      { word: "arrive", translations: { en: "get to a place", ru: "прибывать", de: "ankommen", fr: "arriver", nl: "aankomen", ar: "يصل" } },
      { word: "leave", translations: { en: "go away from", ru: "уходить", de: "verlassen", fr: "partir", nl: "vertrekken", ar: "يغادر" } },
    ],
  },
  {
    topic: "B1 · Work & study",
    words: [
      { word: "meeting", translations: { en: "people gathering to talk", ru: "встреча", de: "Besprechung", fr: "réunion", nl: "vergadering", ar: "اجتماع" } },
      { word: "deadline", translations: { en: "the latest time to finish", ru: "срок сдачи", de: "Frist", fr: "échéance", nl: "deadline", ar: "موعد نهائي" } },
      { word: "schedule", translations: { en: "plan of times", ru: "расписание", de: "Zeitplan", fr: "planning", nl: "rooster", ar: "جدول" } },
      { word: "task", translations: { en: "a piece of work", ru: "задача", de: "Aufgabe", fr: "tâche", nl: "taak", ar: "مهمة" } },
      { word: "report", translations: { en: "written account", ru: "отчёт", de: "Bericht", fr: "rapport", nl: "rapport", ar: "تقرير" } },
      { word: "colleague", translations: { en: "a person you work with", ru: "коллега", de: "Kollege", fr: "collègue", nl: "collega", ar: "زميل" } },
      { word: "manager", translations: { en: "person who leads a team", ru: "руководитель", de: "Manager", fr: "responsable", nl: "manager", ar: "مدير" } },
      { word: "salary", translations: { en: "regular pay", ru: "зарплата", de: "Gehalt", fr: "salaire", nl: "salaris", ar: "راتب" } },
      { word: "interview", translations: { en: "formal meeting for a job", ru: "собеседование", de: "Vorstellungsgespräch", fr: "entretien", nl: "sollicitatiegesprek", ar: "مقابلة" } },
      { word: "experience", translations: { en: "knowledge from doing", ru: "опыт", de: "Erfahrung", fr: "expérience", nl: "ervaring", ar: "خبرة" } },
      { word: "skill", translations: { en: "ability to do something", ru: "навык", de: "Fähigkeit", fr: "compétence", nl: "vaardigheid", ar: "مهارة" } },
      { word: "goal", translations: { en: "what you aim for", ru: "цель", de: "Ziel", fr: "objectif", nl: "doel", ar: "هدف" } },
      { word: "improve", translations: { en: "make better", ru: "улучшать", de: "verbessern", fr: "améliorer", nl: "verbeteren", ar: "يحسن" } },
      { word: "achieve", translations: { en: "succeed in doing", ru: "достигать", de: "erreichen", fr: "atteindre", nl: "bereiken", ar: "يحقق" } },
      { word: "succeed", translations: { en: "do well", ru: "преуспевать", de: "gelingen", fr: "réussir", nl: "slagen", ar: "ينجح" } },
      { word: "fail", translations: { en: "not succeed", ru: "терпеть неудачу", de: "scheitern", fr: "échouer", nl: "falen", ar: "يفشل" } },
      { word: "suggest", translations: { en: "put forward an idea", ru: "предлагать", de: "vorschlagen", fr: "suggérer", nl: "voorstellen", ar: "يقترح" } },
      { word: "discuss", translations: { en: "talk about", ru: "обсуждать", de: "besprechen", fr: "discuter", nl: "bespreken", ar: "يناقش" } },
      { word: "solve", translations: { en: "find an answer", ru: "решать", de: "lösen", fr: "résoudre", nl: "oplossen", ar: "يحل" } },
      { word: "avoid", translations: { en: "keep away from", ru: "избегать", de: "vermeiden", fr: "éviter", nl: "vermijden", ar: "يتجنب" } },
      { word: "require", translations: { en: "need or demand", ru: "требовать", de: "erfordern", fr: "exiger", nl: "vereisen", ar: "يتطلب" } },
      { word: "provide", translations: { en: "give what is needed", ru: "предоставлять", de: "bereitstellen", fr: "fournir", nl: "bieden", ar: "يوفر" } },
      { word: "increase", translations: { en: "make larger", ru: "увеличивать", de: "erhöhen", fr: "augmenter", nl: "verhogen", ar: "يزيد" } },
      { word: "reduce", translations: { en: "make smaller", ru: "сокращать", de: "reduzieren", fr: "réduire", nl: "verminderen", ar: "يقلل" } },
      { word: "research", translations: { en: "careful study", ru: "исследование", de: "Forschung", fr: "recherche", nl: "onderzoek", ar: "بحث" } },
      { word: "evidence", translations: { en: "facts that show something", ru: "доказательство", de: "Beweis", fr: "preuve", nl: "bewijs", ar: "دليل" } },
      { word: "opinion", translations: { en: "what someone thinks", ru: "мнение", de: "Meinung", fr: "opinion", nl: "mening", ar: "رأي" } },
      { word: "reason", translations: { en: "why something happens", ru: "причина", de: "Grund", fr: "raison", nl: "reden", ar: "سبب" } },
      { word: "result", translations: { en: "what comes out of it", ru: "результат", de: "Ergebnis", fr: "résultat", nl: "resultaat", ar: "نتيجة" } },
      { word: "advantage", translations: { en: "a good point", ru: "преимущество", de: "Vorteil", fr: "avantage", nl: "voordeel", ar: "ميزة" } },
      { word: "disadvantage", translations: { en: "a bad point", ru: "недостаток", de: "Nachteil", fr: "inconvénient", nl: "nadeel", ar: "عيب" } },
      { word: "compare", translations: { en: "look at differences", ru: "сравнивать", de: "vergleichen", fr: "comparer", nl: "vergelijken", ar: "يقارن" } },
      { word: "describe", translations: { en: "say what it is like", ru: "описывать", de: "beschreiben", fr: "décrire", nl: "beschrijven", ar: "يصف" } },
      { word: "prepare", translations: { en: "get ready", ru: "готовить", de: "vorbereiten", fr: "préparer", nl: "voorbereiden", ar: "يجهز" } },
      { word: "attend", translations: { en: "go to an event", ru: "посещать", de: "teilnehmen", fr: "assister", nl: "bijwonen", ar: "يحضر" } },
      { word: "apply", translations: { en: "make a formal request", ru: "подавать заявку", de: "sich bewerben", fr: "postuler", nl: "solliciteren", ar: "يتقدم بطلب" } },
      { word: "responsible", translations: { en: "in charge of", ru: "ответственный", de: "verantwortlich", fr: "responsable", nl: "verantwoordelijk", ar: "مسؤول" } },
      { word: "reliable", translations: { en: "can be trusted", ru: "надёжный", de: "zuverlässig", fr: "fiable", nl: "betrouwbaar", ar: "موثوق" } },
      { word: "approve", translations: { en: "say yes to", ru: "одобрять", de: "genehmigen", fr: "approuver", nl: "goedkeuren", ar: "يوافق على" } },
      { word: "manage", translations: { en: "be in control of", ru: "управлять", de: "verwalten", fr: "gérer", nl: "beheren", ar: "يدير" } },
    ],
  },
  {
    topic: "B2 · Opinions & abstract",
    words: [
      { word: "assume", translations: { en: "take as true without proof", ru: "предполагать", de: "annehmen", fr: "supposer", nl: "aannemen", ar: "يفترض" } },
      { word: "consider", translations: { en: "think about carefully", ru: "рассматривать", de: "erwägen", fr: "considérer", nl: "overwegen", ar: "يعتبر" } },
      { word: "determine", translations: { en: "find out or decide", ru: "определять", de: "bestimmen", fr: "déterminer", nl: "bepalen", ar: "يحدد" } },
      { word: "emphasise", translations: { en: "give special importance", ru: "подчёркивать", de: "betonen", fr: "souligner", nl: "benadrukken", ar: "يؤكد" } },
      { word: "indicate", translations: { en: "show or point to", ru: "указывать", de: "hinweisen", fr: "indiquer", nl: "aangeven", ar: "يشير" } },
      { word: "interpret", translations: { en: "explain the meaning", ru: "истолковывать", de: "auslegen", fr: "interpréter", nl: "interpreteren", ar: "يفسر" } },
      { word: "obtain", translations: { en: "get", ru: "получать", de: "erhalten", fr: "obtenir", nl: "verkrijgen", ar: "يحصل على" } },
      { word: "occur", translations: { en: "happen", ru: "происходить", de: "auftreten", fr: "se produire", nl: "voorkomen", ar: "يحدث" } },
      { word: "perceive", translations: { en: "become aware of", ru: "воспринимать", de: "wahrnehmen", fr: "percevoir", nl: "waarnemen", ar: "يدرك" } },
      { word: "pursue", translations: { en: "follow or chase", ru: "преследовать", de: "verfolgen", fr: "poursuivre", nl: "nastreven", ar: "يسعى وراء" } },
      { word: "reveal", translations: { en: "make known", ru: "раскрывать", de: "enthüllen", fr: "révéler", nl: "onthullen", ar: "يكشف" } },
      { word: "significant", translations: { en: "important", ru: "значительный", de: "bedeutend", fr: "significatif", nl: "aanzienlijk", ar: "كبير" } },
      { word: "substantial", translations: { en: "large in amount", ru: "существенный", de: "erheblich", fr: "substantiel", nl: "aanzienlijk", ar: "جوهري" } },
      { word: "inevitable", translations: { en: "certain to happen", ru: "неизбежный", de: "unvermeidlich", fr: "inévitable", nl: "onvermijdelijk", ar: "حتمي" } },
      { word: "controversial", translations: { en: "causing disagreement", ru: "спорный", de: "umstritten", fr: "controversé", nl: "controversieel", ar: "مثير للجدل" } },
      { word: "reluctant", translations: { en: "unwilling", ru: "неохотный", de: "widerwillig", fr: "réticent", nl: "aarzelend", ar: "متردد" } },
      { word: "thorough", translations: { en: "complete and careful", ru: "тщательный", de: "gründlich", fr: "approfondi", nl: "grondig", ar: "شامل" } },
      { word: "accurate", translations: { en: "exactly right", ru: "точный", de: "genau", fr: "exact", nl: "nauwkeurig", ar: "دقيق" } },
      { word: "relevant", translations: { en: "connected to the matter", ru: "уместный", de: "relevant", fr: "pertinent", nl: "relevant", ar: "ذو صلة" } },
      { word: "sufficient", translations: { en: "enough", ru: "достаточный", de: "ausreichend", fr: "suffisant", nl: "voldoende", ar: "كاف" } },
      { word: "crucial", translations: { en: "extremely important", ru: "решающий", de: "entscheidend", fr: "crucial", nl: "cruciaal", ar: "حاسم" } },
      { word: "approach", translations: { en: "a way of dealing with", ru: "подход", de: "Ansatz", fr: "approche", nl: "aanpak", ar: "نهج" } },
      { word: "attitude", translations: { en: "a way of thinking", ru: "отношение", de: "Einstellung", fr: "attitude", nl: "houding", ar: "موقف" } },
      { word: "consequence", translations: { en: "a result of an action", ru: "последствие", de: "Folge", fr: "conséquence", nl: "gevolg", ar: "نتيجة" } },
      { word: "assumption", translations: { en: "something taken as true", ru: "допущение", de: "Annahme", fr: "hypothèse", nl: "aanname", ar: "افتراض" } },
      { word: "estimate", translations: { en: "a rough calculation", ru: "оценка", de: "Schätzung", fr: "estimation", nl: "schatting", ar: "تقدير" } },
      { word: "tendency", translations: { en: "a usual way of behaving", ru: "тенденция", de: "Tendenz", fr: "tendance", nl: "neiging", ar: "ميل" } },
      { word: "bias", translations: { en: "unfair preference", ru: "предвзятость", de: "Voreingenommenheit", fr: "parti pris", nl: "vooroordeel", ar: "تحيز" } },
      { word: "framework", translations: { en: "a basic structure", ru: "структура", de: "Rahmen", fr: "cadre", nl: "kader", ar: "إطار" } },
      { word: "insight", translations: { en: "deep understanding", ru: "понимание", de: "Einblick", fr: "aperçu", nl: "inzicht", ar: "بصيرة" } },
    ],
  },
  {
    topic: "Phrasal verbs",
    words: [
      { word: "give up", translations: { en: "stop trying", ru: "сдаваться", de: "aufgeben", fr: "abandonner", nl: "opgeven", ar: "يستسلم" } },
      { word: "look for", translations: { en: "try to find", ru: "искать", de: "suchen", fr: "chercher", nl: "zoeken", ar: "يبحث عن" } },
      { word: "look after", translations: { en: "take care of", ru: "заботиться о", de: "sich kümmern um", fr: "s'occuper de", nl: "zorgen voor", ar: "يعتني بـ" } },
      { word: "find out", translations: { en: "discover", ru: "выяснять", de: "herausfinden", fr: "découvrir", nl: "uitvinden", ar: "يكتشف" } },
      { word: "turn on", translations: { en: "start a device", ru: "включать", de: "einschalten", fr: "allumer", nl: "aanzetten", ar: "يشغل" } },
      { word: "turn off", translations: { en: "stop a device", ru: "выключать", de: "ausschalten", fr: "éteindre", nl: "uitzetten", ar: "يطفئ" } },
      { word: "put off", translations: { en: "delay", ru: "откладывать", de: "verschieben", fr: "reporter", nl: "uitstellen", ar: "يؤجل" } },
      { word: "take off", translations: { en: "remove; leave the ground", ru: "снимать; взлетать", de: "abheben", fr: "décoller", nl: "opstijgen", ar: "يقلع" } },
      { word: "get up", translations: { en: "rise from bed", ru: "вставать", de: "aufstehen", fr: "se lever", nl: "opstaan", ar: "ينهض" } },
      { word: "come back", translations: { en: "return", ru: "возвращаться", de: "zurückkommen", fr: "revenir", nl: "terugkomen", ar: "يعود" } },
      { word: "go on", translations: { en: "continue", ru: "продолжать", de: "weitermachen", fr: "continuer", nl: "doorgaan", ar: "يستمر" } },
      { word: "carry out", translations: { en: "perform a task", ru: "выполнять", de: "durchführen", fr: "effectuer", nl: "uitvoeren", ar: "ينفذ" } },
      { word: "point out", translations: { en: "draw attention to", ru: "указывать на", de: "hinweisen auf", fr: "signaler", nl: "wijzen op", ar: "يشير إلى" } },
      { word: "set up", translations: { en: "establish or arrange", ru: "учреждать", de: "einrichten", fr: "mettre en place", nl: "opzetten", ar: "ينشئ" } },
      { word: "deal with", translations: { en: "handle", ru: "иметь дело с", de: "umgehen mit", fr: "gérer", nl: "omgaan met", ar: "يتعامل مع" } },
      { word: "bring up", translations: { en: "raise a topic; rear a child", ru: "поднимать тему", de: "ansprechen", fr: "aborder", nl: "ter sprake brengen", ar: "يطرح" } },
      { word: "run out of", translations: { en: "have no more left", ru: "заканчиваться", de: "ausgehen", fr: "manquer de", nl: "opraken", ar: "ينفد" } },
      { word: "catch up", translations: { en: "reach the same level", ru: "догонять", de: "aufholen", fr: "rattraper", nl: "inhalen", ar: "يلحق" } },
      { word: "work out", translations: { en: "turn out well; exercise", ru: "получаться; тренироваться", de: "klappen", fr: "fonctionner", nl: "lukken", ar: "ينجح" } },
      { word: "figure out", translations: { en: "understand after thinking", ru: "разобраться", de: "herausfinden", fr: "comprendre", nl: "uitdokteren", ar: "يفهم" } },
    ],
  },
  {
    topic: "Business",
    words: [
      { word: "negotiate", translations: { en: "discuss to reach a deal", ru: "вести переговоры", de: "verhandeln", fr: "négocier", nl: "onderhandelen", ar: "يتفاوض" } },
      { word: "contract", translations: { en: "a legal agreement", ru: "договор", de: "Vertrag", fr: "contrat", nl: "contract", ar: "عقد" } },
      { word: "invoice", translations: { en: "a bill for goods", ru: "счёт", de: "Rechnung", fr: "facture", nl: "factuur", ar: "فاتورة" } },
      { word: "budget", translations: { en: "money set aside", ru: "бюджет", de: "Budget", fr: "budget", nl: "budget", ar: "ميزانية" } },
      { word: "revenue", translations: { en: "money coming in", ru: "выручка", de: "Umsatz", fr: "chiffre d'affaires", nl: "omzet", ar: "إيرادات" } },
      { word: "profit", translations: { en: "money gained", ru: "прибыль", de: "Gewinn", fr: "bénéfice", nl: "winst", ar: "ربح" } },
      { word: "loss", translations: { en: "money lost", ru: "убыток", de: "Verlust", fr: "perte", nl: "verlies", ar: "خسارة" } },
      { word: "client", translations: { en: "a customer", ru: "клиент", de: "Kunde", fr: "client", nl: "klant", ar: "عميل" } },
      { word: "supplier", translations: { en: "a company that supplies", ru: "поставщик", de: "Lieferant", fr: "fournisseur", nl: "leverancier", ar: "مورد" } },
      { word: "launch", translations: { en: "start something new", ru: "запуск", de: "Markteinführung", fr: "lancement", nl: "lancering", ar: "إطلاق" } },
      { word: "deliver", translations: { en: "bring goods to someone", ru: "поставлять", de: "liefern", fr: "livrer", nl: "leveren", ar: "يسلم" } },
      { word: "forecast", translations: { en: "a prediction", ru: "прогноз", de: "Prognose", fr: "prévision", nl: "prognose", ar: "توقع" } },
      { word: "target", translations: { en: "a result to aim for", ru: "цель", de: "Ziel", fr: "cible", nl: "doel", ar: "هدف" } },
      { word: "competitor", translations: { en: "a rival company", ru: "конкурент", de: "Konkurrent", fr: "concurrent", nl: "concurrent", ar: "منافس" } },
      { word: "agenda", translations: { en: "list of meeting topics", ru: "повестка", de: "Tagesordnung", fr: "ordre du jour", nl: "agenda", ar: "جدول أعمال" } },
      { word: "invest", translations: { en: "put money in", ru: "инвестировать", de: "investieren", fr: "investir", nl: "investeren", ar: "يستثمر" } },
      { word: "negotiation", translations: { en: "the act of negotiating", ru: "переговоры", de: "Verhandlung", fr: "négociation", nl: "onderhandeling", ar: "مفاوضات" } },
      { word: "deadline extension", translations: { en: "more time to finish", ru: "продление срока", de: "Fristverlängerung", fr: "report d'échéance", nl: "uitstel", ar: "تمديد الموعد" } },
      { word: "stakeholder", translations: { en: "a party with an interest", ru: "заинтересованная сторона", de: "Interessengruppe", fr: "partie prenante", nl: "belanghebbende", ar: "صاحب مصلحة" } },
      { word: "merger", translations: { en: "two companies joining", ru: "слияние", de: "Fusion", fr: "fusion", nl: "fusie", ar: "اندماج" } },
    ],
  },
  {
    topic: "Travel & places",
    words: [
      { word: "journey", translations: { en: "act of travelling", ru: "поездка", de: "Reise", fr: "trajet", nl: "reis", ar: "رحلة" } },
      { word: "border", translations: { en: "line between countries", ru: "граница", de: "Grenze", fr: "frontière", nl: "grens", ar: "حدود" } },
      { word: "passport", translations: { en: "travel document", ru: "паспорт", de: "Reisepass", fr: "passeport", nl: "paspoort", ar: "جواز سفر" } },
      { word: "accommodation", translations: { en: "place to stay", ru: "жильё", de: "Unterkunft", fr: "hébergement", nl: "accommodatie", ar: "إقامة" } },
      { word: "delay", translations: { en: "later than planned", ru: "задержка", de: "Verspätung", fr: "retard", nl: "vertraging", ar: "تأخير" } },
      { word: "departure", translations: { en: "act of leaving", ru: "отправление", de: "Abfahrt", fr: "départ", nl: "vertrek", ar: "مغادرة" } },
      { word: "arrival", translations: { en: "act of arriving", ru: "прибытие", de: "Ankunft", fr: "arrivée", nl: "aankomst", ar: "وصول" } },
      { word: "abroad", translations: { en: "in another country", ru: "за границей", de: "im Ausland", fr: "à l'étranger", nl: "in het buitenland", ar: "في الخارج" } },
      { word: "sightseeing", translations: { en: "visiting places of interest", ru: "осмотр достопримечательностей", de: "Besichtigung", fr: "tourisme", nl: "bezienswaardigheden bekijken", ar: "مشاهدة المعالم" } },
      { word: "neighbourhood", translations: { en: "area around where you live", ru: "район", de: "Viertel", fr: "quartier", nl: "buurt", ar: "حي" } },
      { word: "countryside", translations: { en: "land outside towns", ru: "сельская местность", de: "Land", fr: "campagne", nl: "platteland", ar: "ريف" } },
      { word: "coast", translations: { en: "land next to the sea", ru: "побережье", de: "Küste", fr: "côte", nl: "kust", ar: "ساحل" } },
      { word: "mountain", translations: { en: "very high land", ru: "гора", de: "Berg", fr: "montagne", nl: "berg", ar: "جبل" } },
      { word: "bridge", translations: { en: "crosses a river or road", ru: "мост", de: "Brücke", fr: "pont", nl: "brug", ar: "جسر" } },
    ],
  },
  {
    topic: "Feelings & character",
    words: [
      { word: "confident", translations: { en: "sure of yourself", ru: "уверенный", de: "selbstbewusst", fr: "confiant", nl: "zelfverzekerd", ar: "واثق" } },
      { word: "shy", translations: { en: "nervous with people", ru: "застенчивый", de: "schüchtern", fr: "timide", nl: "verlegen", ar: "خجول" } },
      { word: "generous", translations: { en: "willing to give", ru: "щедрый", de: "großzügig", fr: "généreux", nl: "gul", ar: "كريم" } },
      { word: "honest", translations: { en: "telling the truth", ru: "честный", de: "ehrlich", fr: "honnête", nl: "eerlijk", ar: "صادق" } },
      { word: "patient", translations: { en: "able to wait calmly", ru: "терпеливый", de: "geduldig", fr: "patient", nl: "geduldig", ar: "صبور" } },
      { word: "stubborn", translations: { en: "refusing to change", ru: "упрямый", de: "stur", fr: "têtu", nl: "koppig", ar: "عنيد" } },
      { word: "curious", translations: { en: "wanting to know", ru: "любопытный", de: "neugierig", fr: "curieux", nl: "nieuwsgierig", ar: "فضولي" } },
      { word: "anxious", translations: { en: "worried", ru: "тревожный", de: "ängstlich", fr: "anxieux", nl: "angstig", ar: "قلق" } },
      { word: "proud", translations: { en: "pleased with an achievement", ru: "гордый", de: "stolz", fr: "fier", nl: "trots", ar: "فخور" } },
      { word: "grateful", translations: { en: "thankful", ru: "благодарный", de: "dankbar", fr: "reconnaissant", nl: "dankbaar", ar: "ممتن" } },
      { word: "disappointed", translations: { en: "sad it did not happen", ru: "разочарованный", de: "enttäuscht", fr: "déçu", nl: "teleurgesteld", ar: "محبط" } },
      { word: "surprised", translations: { en: "not expecting it", ru: "удивлённый", de: "überrascht", fr: "surpris", nl: "verrast", ar: "متفاجئ" } },
      { word: "lonely", translations: { en: "unhappy being alone", ru: "одинокий", de: "einsam", fr: "seul", nl: "eenzaam", ar: "وحيد" } },
      { word: "relaxed", translations: { en: "calm, not worried", ru: "расслабленный", de: "entspannt", fr: "détendu", nl: "ontspannen", ar: "مرتاح" } },
      { word: "ambitious", translations: { en: "wanting success", ru: "амбициозный", de: "ehrgeizig", fr: "ambitieux", nl: "ambitieus", ar: "طموح" } },
    ],
  },
  {
    topic: "Food & drink",
    words: [
      { word: "breakfast", translations: { en: "first meal of the day", ru: "завтрак", de: "Frühstück", fr: "petit-déjeuner", nl: "ontbijt", ar: "فطور" } },
      { word: "lunch", translations: { en: "midday meal", ru: "обед", de: "Mittagessen", fr: "déjeuner", nl: "lunch", ar: "غداء" } },
      { word: "dinner", translations: { en: "evening meal", ru: "ужин", de: "Abendessen", fr: "dîner", nl: "diner", ar: "عشاء" } },
      { word: "meat", translations: { en: "flesh eaten as food", ru: "мясо", de: "Fleisch", fr: "viande", nl: "vlees", ar: "لحم" } },
      { word: "fish", translations: { en: "animal that lives in water", ru: "рыба", de: "Fisch", fr: "poisson", nl: "vis", ar: "سمك" } },
      { word: "vegetable", translations: { en: "plant grown for food", ru: "овощ", de: "Gemüse", fr: "légume", nl: "groente", ar: "خضار" } },
      { word: "fruit", translations: { en: "sweet part of a plant", ru: "фрукт", de: "Obst", fr: "fruit", nl: "fruit", ar: "فاكهة" } },
      { word: "rice", translations: { en: "small white grain", ru: "рис", de: "Reis", fr: "riz", nl: "rijst", ar: "أرز" } },
      { word: "cheese", translations: { en: "food made from milk", ru: "сыр", de: "Käse", fr: "fromage", nl: "kaas", ar: "جبن" } },
      { word: "egg", translations: { en: "laid by a bird", ru: "яйцо", de: "Ei", fr: "œuf", nl: "ei", ar: "بيضة" } },
      { word: "sugar", translations: { en: "sweet white substance", ru: "сахар", de: "Zucker", fr: "sucre", nl: "suiker", ar: "سكر" } },
      { word: "salt", translations: { en: "white seasoning", ru: "соль", de: "Salz", fr: "sel", nl: "zout", ar: "ملح" } },
      { word: "coffee", translations: { en: "hot dark drink", ru: "кофе", de: "Kaffee", fr: "café", nl: "koffie", ar: "قهوة" } },
      { word: "tea", translations: { en: "hot drink from leaves", ru: "чай", de: "Tee", fr: "thé", nl: "thee", ar: "شاي" } },
      { word: "juice", translations: { en: "liquid from fruit", ru: "сок", de: "Saft", fr: "jus", nl: "sap", ar: "عصير" } },
      { word: "recipe", translations: { en: "instructions for cooking", ru: "рецепт", de: "Rezept", fr: "recette", nl: "recept", ar: "وصفة" } },
      { word: "taste", translations: { en: "flavour; to try food", ru: "вкус", de: "Geschmack", fr: "goût", nl: "smaak", ar: "طعم" } },
      { word: "delicious", translations: { en: "very good to eat", ru: "вкусный", de: "lecker", fr: "délicieux", nl: "heerlijk", ar: "لذيذ" } },
      { word: "hungry", translations: { en: "needing food", ru: "голодный", de: "hungrig", fr: "affamé", nl: "hongerig", ar: "جائع" } },
      { word: "thirsty", translations: { en: "needing a drink", ru: "испытывающий жажду", de: "durstig", fr: "assoiffé", nl: "dorstig", ar: "عطشان" } },
    ],
  },
  {
    topic: "Home & objects",
    words: [
      { word: "kitchen", translations: { en: "room for cooking", ru: "кухня", de: "Küche", fr: "cuisine", nl: "keuken", ar: "مطبخ" } },
      { word: "bedroom", translations: { en: "room for sleeping", ru: "спальня", de: "Schlafzimmer", fr: "chambre", nl: "slaapkamer", ar: "غرفة نوم" } },
      { word: "bathroom", translations: { en: "room for washing", ru: "ванная", de: "Badezimmer", fr: "salle de bains", nl: "badkamer", ar: "حمام" } },
      { word: "garden", translations: { en: "land with plants", ru: "сад", de: "Garten", fr: "jardin", nl: "tuin", ar: "حديقة" } },
      { word: "floor", translations: { en: "what you walk on", ru: "пол", de: "Boden", fr: "sol", nl: "vloer", ar: "أرضية" } },
      { word: "wall", translations: { en: "upright side of a room", ru: "стена", de: "Wand", fr: "mur", nl: "muur", ar: "جدار" } },
      { word: "roof", translations: { en: "top of a building", ru: "крыша", de: "Dach", fr: "toit", nl: "dak", ar: "سقف" } },
      { word: "key", translations: { en: "opens a lock", ru: "ключ", de: "Schlüssel", fr: "clé", nl: "sleutel", ar: "مفتاح" } },
      { word: "lamp", translations: { en: "gives light", ru: "лампа", de: "Lampe", fr: "lampe", nl: "lamp", ar: "مصباح" } },
      { word: "mirror", translations: { en: "shows your reflection", ru: "зеркало", de: "Spiegel", fr: "miroir", nl: "spiegel", ar: "مرآة" } },
      { word: "towel", translations: { en: "cloth for drying", ru: "полотенце", de: "Handtuch", fr: "serviette", nl: "handdoek", ar: "منشفة" } },
      { word: "blanket", translations: { en: "cover for warmth", ru: "одеяло", de: "Decke", fr: "couverture", nl: "deken", ar: "بطانية" } },
      { word: "shelf", translations: { en: "board for storing things", ru: "полка", de: "Regal", fr: "étagère", nl: "plank", ar: "رف" } },
      { word: "drawer", translations: { en: "sliding box in furniture", ru: "ящик", de: "Schublade", fr: "tiroir", nl: "lade", ar: "درج" } },
      { word: "clock", translations: { en: "shows the time", ru: "часы", de: "Uhr", fr: "horloge", nl: "klok", ar: "ساعة" } },
    ],
  },
  {
    topic: "Clothes & body",
    words: [
      { word: "shirt", translations: { en: "worn on the upper body", ru: "рубашка", de: "Hemd", fr: "chemise", nl: "overhemd", ar: "قميص" } },
      { word: "trousers", translations: { en: "worn on the legs", ru: "брюки", de: "Hose", fr: "pantalon", nl: "broek", ar: "بنطال" } },
      { word: "shoe", translations: { en: "worn on the foot", ru: "туфля", de: "Schuh", fr: "chaussure", nl: "schoen", ar: "حذاء" } },
      { word: "coat", translations: { en: "warm outer garment", ru: "пальто", de: "Mantel", fr: "manteau", nl: "jas", ar: "معطف" } },
      { word: "hat", translations: { en: "worn on the head", ru: "шляпа", de: "Hut", fr: "chapeau", nl: "hoed", ar: "قبعة" } },
      { word: "dress", translations: { en: "one-piece garment", ru: "платье", de: "Kleid", fr: "robe", nl: "jurk", ar: "فستان" } },
      { word: "pocket", translations: { en: "small bag in clothing", ru: "карман", de: "Tasche", fr: "poche", nl: "zak", ar: "جيب" } },
      { word: "head", translations: { en: "top of the body", ru: "голова", de: "Kopf", fr: "tête", nl: "hoofd", ar: "رأس" } },
      { word: "hand", translations: { en: "at the end of the arm", ru: "рука (кисть)", de: "Hand", fr: "main", nl: "hand", ar: "يد" } },
      { word: "eye", translations: { en: "you see with it", ru: "глаз", de: "Auge", fr: "œil", nl: "oog", ar: "عين" } },
      { word: "ear", translations: { en: "you hear with it", ru: "ухо", de: "Ohr", fr: "oreille", nl: "oor", ar: "أذن" } },
      { word: "mouth", translations: { en: "you speak with it", ru: "рот", de: "Mund", fr: "bouche", nl: "mond", ar: "فم" } },
      { word: "heart", translations: { en: "pumps blood", ru: "сердце", de: "Herz", fr: "cœur", nl: "hart", ar: "قلب" } },
      { word: "shoulder", translations: { en: "joins arm to body", ru: "плечо", de: "Schulter", fr: "épaule", nl: "schouder", ar: "كتف" } },
      { word: "knee", translations: { en: "joint in the leg", ru: "колено", de: "Knie", fr: "genou", nl: "knie", ar: "ركبة" } },
    ],
  },
  {
    topic: "Time & numbers",
    words: [
      { word: "hour", translations: { en: "sixty minutes", ru: "час", de: "Stunde", fr: "heure", nl: "uur", ar: "ساعة" } },
      { word: "minute", translations: { en: "sixty seconds", ru: "минута", de: "Minute", fr: "minute", nl: "minuut", ar: "دقيقة" } },
      { word: "second", translations: { en: "very short unit of time", ru: "секунда", de: "Sekunde", fr: "seconde", nl: "seconde", ar: "ثانية" } },
      { word: "half", translations: { en: "one of two equal parts", ru: "половина", de: "Hälfte", fr: "moitié", nl: "helft", ar: "نصف" } },
      { word: "quarter", translations: { en: "one of four equal parts", ru: "четверть", de: "Viertel", fr: "quart", nl: "kwart", ar: "ربع" } },
      { word: "double", translations: { en: "twice as much", ru: "двойной", de: "doppelt", fr: "double", nl: "dubbel", ar: "مضاعف" } },
      { word: "century", translations: { en: "a hundred years", ru: "век", de: "Jahrhundert", fr: "siècle", nl: "eeuw", ar: "قرن" } },
      { word: "season", translations: { en: "spring, summer, autumn, winter", ru: "время года", de: "Jahreszeit", fr: "saison", nl: "seizoen", ar: "فصل" } },
      { word: "spring", translations: { en: "season after winter", ru: "весна", de: "Frühling", fr: "printemps", nl: "lente", ar: "ربيع" } },
      { word: "summer", translations: { en: "hottest season", ru: "лето", de: "Sommer", fr: "été", nl: "zomer", ar: "صيف" } },
      { word: "autumn", translations: { en: "season before winter", ru: "осень", de: "Herbst", fr: "automne", nl: "herfst", ar: "خريف" } },
      { word: "winter", translations: { en: "coldest season", ru: "зима", de: "Winter", fr: "hiver", nl: "winter", ar: "شتاء" } },
      { word: "weekend", translations: { en: "Saturday and Sunday", ru: "выходные", de: "Wochenende", fr: "week-end", nl: "weekend", ar: "عطلة نهاية الأسبوع" } },
      { word: "birthday", translations: { en: "day you were born", ru: "день рождения", de: "Geburtstag", fr: "anniversaire", nl: "verjaardag", ar: "عيد ميلاد" } },
      { word: "anniversary", translations: { en: "yearly date of an event", ru: "годовщина", de: "Jahrestag", fr: "anniversaire", nl: "jubileum", ar: "ذكرى سنوية" } },
    ],
  },
  {
    topic: "Common verbs",
    words: [
      { word: "be", translations: { en: "exist; used as a link verb", ru: "быть", de: "sein", fr: "être", nl: "zijn", ar: "يكون" } },
      { word: "have", translations: { en: "own or hold", ru: "иметь", de: "haben", fr: "avoir", nl: "hebben", ar: "يملك" } },
      { word: "do", translations: { en: "perform an action", ru: "делать", de: "tun", fr: "faire", nl: "doen", ar: "يفعل" } },
      { word: "go", translations: { en: "move to a place", ru: "идти", de: "gehen", fr: "aller", nl: "gaan", ar: "يذهب" } },
      { word: "come", translations: { en: "move towards", ru: "приходить", de: "kommen", fr: "venir", nl: "komen", ar: "يأتي" } },
      { word: "see", translations: { en: "perceive with eyes", ru: "видеть", de: "sehen", fr: "voir", nl: "zien", ar: "يرى" } },
      { word: "hear", translations: { en: "perceive with ears", ru: "слышать", de: "hören", fr: "entendre", nl: "horen", ar: "يسمع" } },
      { word: "speak", translations: { en: "say words", ru: "говорить", de: "sprechen", fr: "parler", nl: "spreken", ar: "يتكلم" } },
      { word: "read", translations: { en: "look at and understand text", ru: "читать", de: "читать", fr: "lire", nl: "lezen", ar: "يقرأ" } },
      { word: "write", translations: { en: "put words on paper", ru: "писать", de: "schreiben", fr: "écrire", nl: "schrijven", ar: "يكتب" } },
      { word: "eat", translations: { en: "take in food", ru: "есть", de: "essen", fr: "manger", nl: "eten", ar: "يأكل" } },
      { word: "drink", translations: { en: "take in liquid", ru: "пить", de: "trinken", fr: "boire", nl: "drinken", ar: "يشرب" } },
      { word: "sleep", translations: { en: "rest with eyes closed", ru: "спать", de: "schlafen", fr: "dormir", nl: "slapen", ar: "ينام" } },
      { word: "buy", translations: { en: "get by paying", ru: "покупать", de: "kaufen", fr: "acheter", nl: "kopen", ar: "يشتري" } },
      { word: "sell", translations: { en: "give for money", ru: "продавать", de: "verkaufen", fr: "vendre", nl: "verkopen", ar: "يبيع" } },
      { word: "give", translations: { en: "hand to someone", ru: "давать", de: "geben", fr: "donner", nl: "geven", ar: "يعطي" } },
      { word: "take", translations: { en: "get hold of", ru: "брать", de: "nehmen", fr: "prendre", nl: "nemen", ar: "يأخذ" } },
      { word: "make", translations: { en: "create", ru: "делать (создавать)", de: "machen", fr: "faire", nl: "maken", ar: "يصنع" } },
      { word: "know", translations: { en: "have information", ru: "знать", de: "wissen", fr: "savoir", nl: "weten", ar: "يعرف" } },
      { word: "think", translations: { en: "use your mind", ru: "думать", de: "denken", fr: "penser", nl: "denken", ar: "يفكر" } },
      { word: "want", translations: { en: "wish for", ru: "хотеть", de: "wollen", fr: "vouloir", nl: "willen", ar: "يريد" } },
      { word: "need", translations: { en: "require", ru: "нуждаться", de: "brauchen", fr: "avoir besoin", nl: "nodig hebben", ar: "يحتاج" } },
      { word: "like", translations: { en: "find pleasant", ru: "нравиться", de: "mögen", fr: "aimer", nl: "leuk vinden", ar: "يحب" } },
      { word: "help", translations: { en: "make it easier for someone", ru: "помогать", de: "helfen", fr: "aider", nl: "helpen", ar: "يساعد" } },
      { word: "work", translations: { en: "do a job", ru: "работать", de: "arbeiten", fr: "travailler", nl: "werken", ar: "يعمل" } },
      { word: "play", translations: { en: "take part in a game", ru: "играть", de: "spielen", fr: "jouer", nl: "spelen", ar: "يلعب" } },
      { word: "learn", translations: { en: "gain knowledge", ru: "учиться", de: "lernen", fr: "apprendre", nl: "leren", ar: "يتعلم" } },
      { word: "teach", translations: { en: "give knowledge", ru: "учить (кого-то)", de: "lehren", fr: "enseigner", nl: "onderwijzen", ar: "يعلّم" } },
      { word: "open", translations: { en: "make not closed", ru: "открывать", de: "öffnen", fr: "ouvrir", nl: "openen", ar: "يفتح" } },
      { word: "close", translations: { en: "shut", ru: "закрывать", de: "schließen", fr: "fermer", nl: "sluiten", ar: "يغلق" } },
      { word: "start", translations: { en: "begin", ru: "начинать", de: "beginnen", fr: "commencer", nl: "beginnen", ar: "يبدأ" } },
      { word: "stop", translations: { en: "cease", ru: "останавливать", de: "stoppen", fr: "arrêter", nl: "stoppen", ar: "يتوقف" } },
      { word: "wait", translations: { en: "stay until something happens", ru: "ждать", de: "warten", fr: "attendre", nl: "wachten", ar: "ينتظر" } },
      { word: "send", translations: { en: "cause to go somewhere", ru: "отправлять", de: "senden", fr: "envoyer", nl: "sturen", ar: "يرسل" } },
      { word: "carry", translations: { en: "hold and move", ru: "нести", de: "tragen", fr: "porter", nl: "dragen", ar: "يحمل" } },
      { word: "build", translations: { en: "make a structure", ru: "строить", de: "bauen", fr: "construire", nl: "bouwen", ar: "يبني" } },
      { word: "break", translations: { en: "separate into pieces", ru: "ломать", de: "brechen", fr: "casser", nl: "breken", ar: "يكسر" } },
      { word: "clean", translations: { en: "remove dirt", ru: "чистить", de: "reinigen", fr: "nettoyer", nl: "schoonmaken", ar: "ينظف" } },
      { word: "change", translations: { en: "make different", ru: "менять", de: "ändern", fr: "changer", nl: "veranderen", ar: "يغير" } },
      { word: "keep", translations: { en: "continue to have", ru: "хранить", de: "behalten", fr: "garder", nl: "houden", ar: "يحتفظ" } },
    ],
  },
  {
    topic: "Adjectives",
    words: [
      { word: "big", translations: { en: "large in size", ru: "большой", de: "groß", fr: "grand", nl: "groot", ar: "كبير" } },
      { word: "small", translations: { en: "little in size", ru: "маленький", de: "klein", fr: "petit", nl: "klein", ar: "صغير" } },
      { word: "long", translations: { en: "great in length", ru: "длинный", de: "lang", fr: "long", nl: "lang", ar: "طويل" } },
      { word: "short", translations: { en: "small in length", ru: "короткий", de: "kurz", fr: "court", nl: "kort", ar: "قصير" } },
      { word: "new", translations: { en: "recently made", ru: "новый", de: "neu", fr: "nouveau", nl: "nieuw", ar: "جديد" } },
      { word: "old", translations: { en: "not new; aged", ru: "старый", de: "alt", fr: "vieux", nl: "oud", ar: "قديم" } },
      { word: "young", translations: { en: "not old", ru: "молодой", de: "jung", fr: "jeune", nl: "jong", ar: "شاب" } },
      { word: "good", translations: { en: "of high quality", ru: "хороший", de: "gut", fr: "bon", nl: "goed", ar: "جيد" } },
      { word: "bad", translations: { en: "of poor quality", ru: "плохой", de: "schlecht", fr: "mauvais", nl: "slecht", ar: "سيء" } },
      { word: "easy", translations: { en: "not difficult", ru: "лёгкий", de: "einfach", fr: "facile", nl: "gemakkelijk", ar: "سهل" } },
      { word: "difficult", translations: { en: "hard to do", ru: "трудный", de: "schwierig", fr: "difficile", nl: "moeilijk", ar: "صعب" } },
      { word: "fast", translations: { en: "moving quickly", ru: "быстрый", de: "schnell", fr: "rapide", nl: "snel", ar: "سريع" } },
      { word: "slow", translations: { en: "not fast", ru: "медленный", de: "langsam", fr: "lent", nl: "langzaam", ar: "بطيء" } },
      { word: "strong", translations: { en: "having power", ru: "сильный", de: "stark", fr: "fort", nl: "sterk", ar: "قوي" } },
      { word: "weak", translations: { en: "lacking power", ru: "слабый", de: "schwach", fr: "faible", nl: "zwak", ar: "ضعيف" } },
      { word: "dirty", translations: { en: "not clean", ru: "грязный", de: "schmutzig", fr: "sale", nl: "vuil", ar: "متسخ" } },
      { word: "quiet", translations: { en: "making little noise", ru: "тихий", de: "leise", fr: "calme", nl: "stil", ar: "هادئ" } },
      { word: "loud", translations: { en: "making much noise", ru: "громкий", de: "laut", fr: "fort", nl: "luid", ar: "صاخب" } },
      { word: "beautiful", translations: { en: "very attractive", ru: "красивый", de: "schön", fr: "beau", nl: "mooi", ar: "جميل" } },
      { word: "safe", translations: { en: "free from danger", ru: "безопасный", de: "sicher", fr: "sûr", nl: "veilig", ar: "آمن" } },
      { word: "dangerous", translations: { en: "likely to cause harm", ru: "опасный", de: "gefährlich", fr: "dangereux", nl: "gevaarlijk", ar: "خطير" } },
      { word: "empty", translations: { en: "containing nothing", ru: "пустой", de: "leer", fr: "vide", nl: "leeg", ar: "فارغ" } },
      { word: "full", translations: { en: "containing all it can", ru: "полный", de: "voll", fr: "plein", nl: "vol", ar: "ممتلئ" } },
      { word: "heavy", translations: { en: "weighing a lot", ru: "тяжёлый", de: "schwer", fr: "lourd", nl: "zwaar", ar: "ثقيل" } },
      { word: "light", translations: { en: "not heavy", ru: "лёгкий (по весу)", de: "leicht", fr: "léger", nl: "licht", ar: "خفيف" } },
      { word: "similar", translations: { en: "almost the same", ru: "похожий", de: "ähnlich", fr: "similaire", nl: "vergelijkbaar", ar: "مشابه" } },
      { word: "different", translations: { en: "not the same", ru: "другой", de: "anders", fr: "différent", nl: "anders", ar: "مختلف" } },
      { word: "possible", translations: { en: "able to happen", ru: "возможный", de: "möglich", fr: "possible", nl: "mogelijk", ar: "ممكن" } },
      { word: "necessary", translations: { en: "needed", ru: "необходимый", de: "notwendig", fr: "nécessaire", nl: "noodzakelijk", ar: "ضروري" } },
    ],
  },
  {
    topic: "Connectors",
    words: [
      { word: "because", translations: { en: "for the reason that", ru: "потому что", de: "weil", fr: "parce que", nl: "omdat", ar: "لأن" } },
      { word: "although", translations: { en: "in spite of the fact", ru: "хотя", de: "obwohl", fr: "bien que", nl: "hoewel", ar: "على الرغم من" } },
      { word: "however", translations: { en: "but; nevertheless", ru: "однако", de: "jedoch", fr: "cependant", nl: "echter", ar: "لكن" } },
      { word: "therefore", translations: { en: "for that reason", ru: "поэтому", de: "daher", fr: "donc", nl: "daarom", ar: "لذلك" } },
      { word: "moreover", translations: { en: "in addition", ru: "более того", de: "außerdem", fr: "de plus", nl: "bovendien", ar: "علاوة على ذلك" } },
      { word: "instead", translations: { en: "in place of", ru: "вместо", de: "stattdessen", fr: "au lieu de", nl: "in plaats daarvan", ar: "بدلا من" } },
      { word: "besides", translations: { en: "as well as", ru: "кроме того", de: "außerdem", fr: "en outre", nl: "bovendien", ar: "إلى جانب" } },
      { word: "otherwise", translations: { en: "if not", ru: "иначе", de: "sonst", fr: "sinon", nl: "anders", ar: "وإلا" } },
      { word: "while", translations: { en: "during the time that", ru: "пока", de: "während", fr: "pendant que", nl: "terwijl", ar: "بينما" } },
      { word: "unless", translations: { en: "except if", ru: "если не", de: "es sei denn", fr: "à moins que", nl: "tenzij", ar: "ما لم" } },
      { word: "whereas", translations: { en: "in contrast", ru: "тогда как", de: "wohingegen", fr: "tandis que", nl: "terwijl", ar: "في حين" } },
      { word: "despite", translations: { en: "in spite of", ru: "несмотря на", de: "trotz", fr: "malgré", nl: "ondanks", ar: "رغم" } },
      { word: "furthermore", translations: { en: "in addition", ru: "кроме того", de: "ferner", fr: "de plus", nl: "verder", ar: "إضافة إلى ذلك" } },
      { word: "nevertheless", translations: { en: "in spite of that", ru: "тем не менее", de: "dennoch", fr: "néanmoins", nl: "niettemin", ar: "مع ذلك" } },
      { word: "thus", translations: { en: "in this way", ru: "таким образом", de: "somit", fr: "ainsi", nl: "aldus", ar: "وبالتالي" } },
    ],
  },
];
